### ISSUE TITLE
Crying Obsidian

### ISSUE THREAD

**Issue by ThunbergOlle** [HTS-Earth/CraftingRecipes#2]
Recipe: 
O = Obsidian, X = no material (air)

```
X O X
O O O
X O X
```

**Comment by ThunbergOlle** [comment]
Are there more recipes we may wanna add ? @Eldafint , @iChoob

**Comment by ThunbergOlle** [comment]
From discord: 

iChoob: @miljonmannen You said something about more recipes on the repo, I think that maybe a recipe for chain armor might be nice? Maybe horse equipment as well, and name tags could be a nice addition as well. Those are things I feel should have recipes but don't in vanilla

**Comment by ThunbergOlle** [comment]
@iChoob You can add lapiz to the Crying obsidian recipe.

**Comment by iChoob** [comment]
For this specific recipe I would do:

O = Obsidian
L = Lapiz
```
L O L 
O L O 
L O L 
```

Does this sound alright?

**Comment by ThunbergOlle** [comment]
It sounds good! 👍

**Comment by ThunbergOlle** [comment]
@DavidssonSimon and @Eldafint thoughts?

**Comment by Eldafint** [comment]
I think it would be better to do it like this:

```
O L O
L X L
O L O
```

And it would give you 4 crying obsidian so 1 per obsidian + lapiz.
